package org.example;

public class Metodos {

    //PRIVATE: VISÍVEL APENAS NA MESMA CLASSE
    //PUBLIC: VISIVEL EM QUALQUER CLASSES
    //PROTECTED: VISIVEL POR CLASSES NO MESMO PACOTE E SUBCLASSES
    //STATIC:
}
